const Texts = {
  pl: {
    buttonRegistration: "Zarejestruj się",
    registrationTitle: "Rejestracja",
    inputEmail: "Email",
    inputPassword: "Hasło",
    inputName: "Imię",
    inputSurname: "Nazwisko",
    inputRepeatPassword: "Powtórz hasło",
    inputPhoneNumber: "Numer telefonu",
    minLetter: "Minimum 6 znaków",
    min3Letter: "Minimum 3 znaki",
    min9Letter: "Minimum 9 znaków",
    registrationFacebook: "Zarejestruj się za pomoca facebook",
    registrationGoogle: "Zarejestruj się za pomoca google",
    errorRegistration: "Błąd podczas rejestracji",
    emailBussy: "Adres email jest zajęty",
    passwordMustBeTheSame: "Hasła muszą być takie same",
    checkboxAcceptRegulation: "Zaakceptuj regulamin",
    regulations: "Regulamin",
    somethingWentWrong: "Coś poszło nie tak",
    warningAcceptRegulation: "Zaakceptuj regulamin, aby dokończyć rezerwację",
  },
  en: {
    buttonRegistration: "Register",
    registrationTitle: "Registration",
    inputEmail: "Email",
    inputName: "Name",
    inputSurname: "Surname",
    inputRepeatPassword: "Repeat password",
    inputPhoneNumber: "Phone number",
    inputPassword: "Password",
    minLetter: "6 characters minimum",
    min3Letter: "3 characters minimum",
    min9Letter: "9 characters minimum",
    registrationFacebook: "Register with facebook",
    registrationGoogle: "Register with google",
    errorRegistration: "Error during registration",
    emailBussy: "Email address is in use",
    passwordMustBeTheSame: "Passwords must be the same",
    checkboxAcceptRegulation: "Accept the terms and conditions",
    regulations: "Regulations",
    somethingWentWrong: "Something went wrong",
    warningAcceptRegulation:
      "Accept the terms and conditions to complete your booking",
  },
};

export default Texts;
