const Texts = {
  pl: {
    errorFetchProduct: "Błąd podczas pobierania oferty",
    addedCoupon: "Zastosowany kupon",
    invoiceFrom: "Faktury VAT z dnia",
    cancelSubscription: "Anuluj subskrypcję",
    productName: "Nazwa produktu",
    countPoints: "Liczba Meetsy punktów",
    countMonthsSubscription: "Liczba dodatkowych miesięcy ważności konta",
    countSMS: "Liczba SMS",
    startPrice: "Cena bazowa",
    priceAfter: "Cena po obniżce za pierwszy miesiąc",
    price: "Cena",
    paid: "Zapłacono",
    canceled: "Anulowano",
    noPaid: "Nie zapłacono",
    link: "Link",
    goToPayment: "Przejdz do płatności",
    hasExpired: "Wygasł",
    invoice: "Faktura VAT",
    paymentsAndScubscriptions: "Płatności oraz subskrypcje",
    status: "Status",
  },
  en: {
    errorFetchProduct: "Error downloading the offer",
    addedCoupon: "Coupon applied",
    invoiceFrom: "VAT invoices dated",
    cancelSubscription: "Cancel subscription",
    productName: "Product name",
    countPoints: "Meetsy number of points",
    countMonthsSubscription:
      "Number of additional months for the account validity",
    countSMS: "Number of SMS",
    startPrice: "Base price",
    priceAfter: "Discounted price for the first month",
    price: "Price",
    paid: "Paid",
    canceled: "Canceled",
    noPaid: "Is not paid",
    link: "Link",
    goToPayment: "Go to payment",
    hasExpired: "Has expired",
    invoice: "VAT invoice",
    paymentsAndScubscriptions: "Payments and subscriptions",
    status: "Status",
  },
};

export default Texts;
