export const AccountPageTexts = {
  pl: {
    title: "Ustawienia konta",
    confirmEmailAdress: "Potwierdz adres e-mail",
    accountPassword: "Ustaw hasło do konta",
    addPhoneNumber: "Wprowadz numer telefonu",
    confirmPhoneNumber: "Potwierdz numer telefonu",
    deleteAccount: "Usuń konto",
    changePassword: "Zmień hasło",
    changePhone: "Zmień numer telefonu",
    confirmNewPhone: "Potwierdz nowy numer telefonu",
    changeEmail: "Zmień adres e-mail",
    confirmNewEmail: "Potwierdz nowy adres e-mail",
    editAccount: "Edytuj konto",
    manageConsents: "Zarządzaj zgodami",
  },
  en: {
    title: "Account settings",
    confirmEmailAdress: "Confirm email address",
    accountPassword: "Set an account password",
    addPhoneNumber: "Enter a phone number",
    confirmPhoneNumber: "Confirm the phone number",
    deleteAccount: "Delete account",
    changePassword: "Change Password",
    changePhone: "Change the phone number",
    confirmNewPhone: "Confirm the new phone number",
    changeEmail: "Change e-mail address",
    confirmNewEmail: "Confirm the new email address",
    editAccount: "Edit account",
    manageConsents: "Manage consents",
  },
};
