const Texts = {
  pl: {
    inputEmail: "Adres e-mail firmy",
    searchCompany: "Wyszukaj firmę",
    company: "Firma:",
    noFindedCompany: "Brak znalezionej firmy",
    companyId: "ID firmy:",
    companyName: "Nazwa firmy:",
    accountBanned: "Konto zablokowane:",
    email: "Email:",
    emailIsConfirmed: "Adres email jest potwierdzony:",
    emailToConfierm: "Email do potwierdzenia:",
    nip: "NIP:",
    country: "Państwo:",
    postalCode: "Kod pocztowy:",
    city: "Miasto:",
    district: "Dzielnica:",
    street: "Ulica:",
    link: "Link:",
    locationOnMaps: "Lokalizacja na mapach:",
    phoneNumber: "Numer telefonu:",
    phoneIsConfirmed: "Numer telefonu jest potwierdzony:",
    phoneTosConfirm: "Numer telefonu do potwierdzenia:",
    dateLastSendSMSConfirmPhone:
      "Data ostatniego wysłanego SMS do potwierdzenia numeru telefonu:",
    dateUpdatedCompany: "Data aktualizacji firmy:",
    dateCreatedCompany: "Data utworzenia firmy:",
    addWorkerToCompany: "Dodaj pracownika do firmy",
    unBanCompany: "Odblokuj firmę",
    banCompany: "Zablokuj firmę",
    workers: "Pracownicy",
  },
  en: {
    inputEmail: "Company email address",
    searchCompany: "Search for a company",
    company: "Company:",
    noFindedCompany: "No company found",
    companyId: "Company ID:",
    companyName: "Company name:",
    accountBanned: "Blocked account:",
    email: "Email:",
    emailIsConfirmed: "The email address is confirmed:",
    emailToConfierm: "Email for confirmation:",
    nip: "NIP:",
    country: "Country:",
    postalCode: "ZIP code:",
    city: "City:",
    district: "District:",
    street: "Street:",
    link: "Link:",
    locationOnMaps: "Location on maps:",
    phoneNumber: "Phone number:",
    phoneIsConfirmed: "The phone number is confirmed:",
    phoneTosConfirm: "The phone number to be confirmed:",
    dateLastSendSMSConfirmPhone:
      "Date of the last SMS sent to confirm the phone number:",
    dateUpdatedCompany: "Company update date:",
    dateCreatedCompany: "Company creation date:",
    addWorkerToCompany: "Add an employee to the company",
    unBanCompany: "Unban the company",
    banCompany: "Block the company",
    workers: "Workers",
  },
};

export default Texts;
