const Texts = {
  pl: {
    buttonRegistration: "Utwórz firmę",
    registrationTitle: "Tworzenie firmy",
    inputEmail: "Email firmowy",
    inputNameCompany: "Nazwa firmy",
    inputPostalCode: "Kod pocztowy",
    inputDistrict: "Dzielnica",
    inputStreet: "Ulica",
    inputCity: "Miasto",
    inputNip: "Nip",
    minLetter: "Minimum 6 znaków",
    inputPhoneNumber: "Numer telefonu",
    min3Letter: "Minimum 3 znaki",
    min5Letter: "Minimum 5 znaki",
    min9Letter: "Minimum 9 znaków",
    errorRegistration: "Błąd podczas rejestracji",
    emailBussy: "Adres email jest zajęty",
    checkboxAcceptRegulation: "Zaakceptuj regulamin",
    regulations: "Regulamin",
    somethingWentWrong: "Coś poszło nie tak",
    warningAcceptRegulation: "Zaakceptuj regulamin, aby dokończyć rezerwację",
    badPostalCode: "Błędny kod pocztowy",
  },
  en: {
    buttonRegistration: "Create a company",
    registrationTitle: "Registration",
    inputEmail: "Business email",
    inputNameCompany: "Company creation",
    inputPostalCode: "Postal code",
    inputDistrict: "District",
    inputStreet: "Street",
    inputCity: "City",
    inputNip: "Nip",
    inputPhoneNumber: "Phone number",
    minLetter: "6 characters minimum",
    min3Letter: "3 characters minimum",
    min5Letter: "5 characters minimum",
    min9Letter: "9 characters minimum",
    errorRegistration: "Error during registration",
    emailBussy: "Email address is in use",
    checkboxAcceptRegulation: "Accept the terms and conditions",
    regulations: "Regulations",
    somethingWentWrong: "Something went wrong",
    warningAcceptRegulation:
      "Accept the terms and conditions to complete your booking",
    badPostalCode: "Wrong zip code",
  },
};

export default Texts;
